version: "3.9"

services:
  hermes-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hermes-backend-stage
    restart: unless-stopped
    volumes:
      - storage_log:/var/www/html/storage/logs
      - var_log:/var/log
    ports:
      - '8081:80'
      - '6002:6002'

volumes:
   storage_log:
   var_log:

