version: "3.9"

services:

#    app:
#        build:
#            args:
#                user: hermes
#                uid: 1000
#            context: ./
#            dockerfile: Dockerfile
#        image: hermes-backend
#        container_name: hermes-backend
#        restart: unless-stopped
#        working_dir: /var/www/
#        volumes:
#            - ./:/var/www/
#        networks:
#            - hermes

    mongodb:
        image: mongo:latest
        container_name: hermes-mongodb
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - dbdata:/data/db
        networks:
            - hermes

    nginx:
        image: nginx:latest
        container_name: hermes-nginx
        restart: unless-stopped
        ports:
            - 8000:8000
            - 443:443
        volumes:
            - ./:/var/www/
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - hermes

    redis:
        image: redis:latest
        container_name: hermes-redis
        restart: unless-stopped
        tty: true
        ports:
            - 6379:6379
        volumes:
            - dbdata:/data
        networks:
            - hermes

networks:
    hermes:
        driver: bridge

volumes:
    dbdata:
        driver: local
