#Base Image
FROM php:7.4-fpm

LABEL maintainer="Ali Khedmati"

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies and update the system.
RUN apt-get update \
 && apt-get install -y supervisor git curl zip unzip libzip-dev libpng-dev libonig-dev libxml2-dev \
 && pecl install mongodb \
 && echo "extension=mongodb.so" > $PHP_INI_DIR/conf.d/mongo.ini

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl gd bcmath json xml

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

#Supervisord
COPY ./docker/supervisor/hermes.conf /etc/supervisor/conf.d/supervisord.conf

#PHP
COPY ./docker/php/hermes.ini $PHP_INI_DIR/conf.d/hermes.ini

# Set working directory
WORKDIR /var/www/hermes-backend

# Set user.
USER $user

## Install composer dependencies + artisan commands.
#RUN composer install --optimize-autoloader --no-dev && \
#    php artisan key:generate && \
#    php artisan storage:link && \
#    php artisan optimize && \
#    php artisan migrate
