#Base Image
FROM php:8.1-fpm

LABEL maintainer="Ali Khedmati"

# Arguments defined in docker-compose.yml
ARG user=hermes
ARG uid=1000

# Install system dependencies and update the system.
RUN apt-get update \
 && apt-get install -y git curl zip unzip libzip-dev libpng-dev libonig-dev libxml2-dev libcurl4-openssl-dev pkg-config libssl-dev \
 && pecl install redis mongodb swoole\
 && docker-php-ext-enable redis mongodb swoole

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl gd bcmath xml

# Get latest Composer
COPY --from=composer:2.3 /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -m  -d /home/$user $user

RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

#Supervisord
RUN apt-get update && apt-get install supervisor htop -y

COPY ./docker/supervisor/hermes.conf /etc/supervisor/conf.d/supervisord.conf

RUN touch /var/log/supervisor/supervisord.log

RUN chmod -R 777 /var/log/supervisor /var/run

CMD /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf

#PHP
COPY ./docker/php/hermes.ini $PHP_INI_DIR/conf.d/hermes.ini

EXPOSE 9000 9581

# Set working directory
WORKDIR /var/www

# Set user.
#USER $user

## Install composer dependencies + artisan commands.
#RUN composer install --optimize-autoloader --no-dev && \
#    php artisan key:generate && \
#    php artisan storage:link && \
#    php artisan optimize && \
#    php artisan migrate
